### ISSUE TITLE
2.22.0 release notes

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#802]
#### Summary:
pulling discussion of 2.22 release notes into its own issue  from here: https://github.com/stan-dev/cmdstan/issues/797#issuecomment-576204588

#### Description:
Proposed release notes summarizing Stan changes don't mention stanc3 compiler -
need to put this at the top

Current proposal:

Features:

- validate_dims in stan::io::var_context vas made a virtual function which allows its implementation for JSON data which is needed to accepts arrays where any dimension is size 0
- replaced Eigen vectors of strings with std::vectorstd::string
- replaced stan::math::domain_error with throw_domain_error
- added const noexcept accessors to the stepsize adaptation class which allows developers to query the adaptation parameters in contexts where it's natural to have a const sampler (logging, serialization, ...)

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
What we want to say about the new compiler:

As of version 2.22, CmdStan has switched to the new Stan-to-C++ compiler, called stanc3. This compiler is intended to be backwards compatible with the existing Stan language and should accept all models that compile under the release 2.21 compiler.  [Troubleshooting instructions](https://github.com/stan-dev/cmdstan/tree/docs_readme_cleanup_stanc3#troubleshooting)

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - hope this helps!

**Comment by rok-cesnovar** [comment]
So for CmdStan its what is written below with the above comment from @mitzimorris on top: 

Features

- switched to using pre-built binary of the Stan compiler written in OCaml
- added printing info on threading and OpenCL when either are used
- adde a new make rule for cleaning up compiled Stan programs

Bugfix: 
- accepts arrays where any dimension is size 0
- cleanup use of Eigen vectors of strings
- makefiles fixes for cases where users delete the model .hpp file

Developer oriented:
- fixed script for running tests
- fixed dependencies and makefiles which now recompile on changes in services
- makefile fixes for cases when changes were done in the stan submodule
- cleanup of hardcoded version numbers


For Stan you have the top-level comment in this issue and for Math its the last comment in this gist: https://gist.github.com/rok-cesnovar/923fcc78139f4331fcb73c28afc7a332#gistcomment-3145261

**Comment by serban-nicusor-toptal** [comment]
Thank you all for helping out with the release notes and cmdstan/stanc3 changes!
I will give it a few more hours so everyone has time to verify if there's something missing and have time to comment/fix. I'll go over the release notes to make sure they're good and if nothing else pops up I'll do the release. 

Math 3.1
Stan/CmdStan/Stanc3 2.22

**Comment by bob-carpenter** [comment]
This looks like a dealbreaker bug for TBB + map_rect:

https://github.com/stan-dev/math/issues/1637

@wds15 --- is the bug still there in 2.22?  Is there any chance it can get fixed before release?  If not, we need to **strongly** discourage users from using multi-threading until it's fixed.

**Comment by wds15** [comment]
@bob-carpenter The issue is still there. I do not think it is critical. What is happening is that some TBB resources do not get de-allocated in the right order. However, this happens after the entire Stan program ran successfully such that no inference is affected at all.

I can look into fixing it by tomorrow if you consider it that urgent. It will not help to discourage users from using threading. The TBB is always turned on - even if you do not use `STAN_THREADS` (but the problem does not seem to occur).

**Comment by bob-carpenter** [comment]
> I can look into fixing it by tomorrow if you consider it that urgent. 

If multithreading segfaults, it's going to take down RStan or PyStan, so yes, I'd consider it a critical bug that needs to be fixed before this release. Or we need to tell people about it very clearly and tell them not to use threading in PyStan or RStan (this may not even be an issue if they haven't caught up yet).

**Comment by rok-cesnovar** [comment]
My opinion is that we should put off the release if this can be fixed in a day. We are already 4 days of target anyways.

**Comment by wds15** [comment]
It's not going to take down Rstan or PyStan as they manage globals differently. The problem only exists whenever the entire globals go out of memory - including the TBB management. This won't happen before everything is done.

...but we can fix it relatively sure within 24h from now. I just do not have time before tomorrow my morning.

**Comment by mitzimorris** [comment]
I would prefer to delay this release if the bug can be fixed within the next 2-3 days.  otherwise, we should do a release and document the bug.
is this now the place where we're discussing release or no?

**Comment by wds15** [comment]
I will try to resolve it tomorrow. We don’t have a dedicated place for release discussions I think.

**Comment by rok-cesnovar** [comment]
The Math PR is close to being merged (<1 hour) but the merge must also then pass the tests and then it will propagate to cmdstan, so everything will be ready this evening New York time or tomorrow CET, which I assume is the timezone @serban-nicusor-toptal is in.

**Comment by rok-cesnovar** [comment]
Everything is ready now. Not sure who needs to give the green light to Nic to proceed with the release? @mitzimorris maybe?

**Comment by seantalts** [comment]
I passed off my responsibility for that to @jgabry for the time being.

**Comment by wds15** [comment]
Do we really need another blessing here? We have decided to release every 3 month after a 1 week feature freeze. We are following that process and just had some delays for good reasons (stanc3 parser + last minute bug). All that is done.

So we are good to go ahead from my view, but maybe I missed that someone with authority has to sign off this... but that's new to me.

**Comment by seantalts** [comment]
Sounds good to me!

**Comment by serban-nicusor-toptal** [comment]
Hey, I will get home in about two hours. Till then there's time to make sure everything is ready. As soon as I get home will start the release process if nothing pops up meanwhile.

**Comment by serban-nicusor-toptal** [comment]
The releases for [Math](https://github.com/stan-dev/math/releases), [Stan](https://github.com/stan-dev/stan/releases), [CmdStan](https://github.com/stan-dev/cmdstan/releases) are now complete. If anyone can take a look to double-check I'll be grateful!

In stan I've referenced `2.22` docs but they don't yet exist in master, there's [this PR](https://github.com/stan-dev/docs/pull/139) in docs for them. If you have some time @mitzimorris please take a look to make sure everything was correctly generated from Jenkins and approve, thank you!

Would anyone mind if I create one issue like this 1-2 weeks before any release so we can coordinate? I think it's a very good way of preparing for a release and making sure everything is alright.

If there is anyting else I should take care of please let me know!

**Comment by rok-cesnovar** [comment]
Thanks @serban-nicusor-toptal 

I think we need to do one minor fix. 

These should remain on nightly: https://github.com/stan-dev/cmdstan/commit/e4928d50b170f3832f791d71d2a55975b1493ce5#diff-0f054d4f459f57b990415bb064749bdaL55

The new link doesnt work anyways: https://github.com/stan-dev/stanc3/releases/download/2.22.0/, should be v2.22.0.

However, we should stick with nightly there, see https://github.com/stan-dev/cmdstan/pull/799#issuecomment-576703881

If someone downloads the tarball, they get the windows-stanc, linux-stanc, mac-stanc binaries in the tarball and cmdstan will use those.
If someone deletes them and tries to build, they get the nightl release. 

This way relesed tarball uses the v2.22.0 stanc3 and develop cmdstan pulls the latest stanc3.

> Would anyone mind if I create one issue like this 1-2 weeks before any release so we can coordinate? I think it's a very good way of preparing for a release and making sure everything is alright.

Yes, please! One in Math, Stan & Cmdstan would be fantastic.

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar Done!

**Comment by rok-cesnovar** [comment]
Can we also update the release tarballs and source files or would that require another release?

**Comment by serban-nicusor-toptal** [comment]
I can re-generate locally, give me a few moments, please.

**Comment by serban-nicusor-toptal** [comment]
So in order for the release to pick up last commit which quickfixed the `nightly` part I had to delete the tag and re-create it pointing to the [correct commit](https://github.com/stan-dev/cmdstan/releases/tag/v2.22.0).
Also rebuilt `cmdstan-2.22.0.tar.gz` from the last tag.
Source code `zip` and `tar.gz` are now reflecting last commit.

**Comment by rok-cesnovar** [comment]
Looks good now! Thanks again @serban-nicusor-toptal. Will close this issue now.

**Comment by jgabry** [comment]
> I passed off my responsibility for that to @jgabry for the time being.

Sorry to be late to chime in here, I've been away. But glad to see the resolution here. Thanks everyone!

**Comment by jpritikin** [comment]
> accepts arrays where any dimension is size 0

Wait, does this mean I can do

```
parameters {
  vector[0] notUsedInThisModel;
}
```

??

**Comment by rok-cesnovar** [comment]
See https://github.com/stan-dev/cmdstan/issues/775 for details on that.
